services:
  mysql:
    #usemysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: mydb
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    container_name: database_test
    ports:
      - "3306:3306"
    volumes:
      #This is the volume that will be mounted
      - ./data:/var/lib/mysql:rw